# Generated by Django 5.2.6 on 2025-10-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_evento_dataf_alter_evento_datai'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/imagens/'),
        ),
    ]
