# Generated by Django 5.2.6 on 2025-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmar_senha',
            field=models.TextField(default='exemplo', max_length=255),
            preserve_default=False,
        ),
    ]
