# Generated by Django 5.2.6 on 2025-11-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_usuario_confirmar_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horarioF',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horarioI',
            field=models.TimeField(),
        ),
    ]
