# Generated by Django 5.2.6 on 2025-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_alter_evento_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
