# Generated by Django 5.2.6 on 2025-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_alter_evento_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='aaaaaa', max_length=6),
            preserve_default=False,
        ),
    ]
