# Generated by Django 5.2.6 on 2025-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_usuario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default='teste', max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='confirmar_senha',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
