# Generated by Django 5.2.6 on 2025-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_alter_usuario_options_remove_usuario_confirmar_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organResp',
            field=models.CharField(max_length=300),
        ),
    ]
